sudo: required
services:
  - docker

language: go

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - go get -u -v github.com/go-task/task/cmd/task

script:
  - STACK=drupal-7 task test
  - STACK=drupal-8 task test
  - STACK=drupal-8-dev task test
  - STACK=grav-1 task test

notifications:
  email: false
