sudo: required
services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - curl -s https://raw.githubusercontent.com/go-task/task/master/install-task.sh | sh

script:
  - STACK=drupal-7 ./bin/task test
  - STACK=drupal-8 ./bin/task test
  - STACK=drupal-8-dev ./bin/task test
  - STACK=grav-1 ./bin/task test

notifications:
  email: false
