version: '2'

tasks:
  test:
    desc: Install, test and stop stack
    cmds:
      - task: install
      - task: test-http
      - task: stop

  download:
    desc: Download stack
    cmds:
      - git clone https://github.com/cleverway/docker-stacks.git
      - mv docker-stacks/{{.STACK}} .
      - rm -rf docker-stacks/

  install:
    desc: Install stack
    cmds:
      - cd {{.STACK}} && task install

  start:
    desc: Start stack
    cmds:
      - cd {{.STACK}} && task start

  stop:
    desc: Stop stack
    cmds:
      - cd {{.STACK}} && task stop

  test-http:
    desc: Test stack via http request at default endpoint
    cmds:
      - curl -I http://localhost:8080/
