version: '2'

tasks:
  test:
    cmds:
      - task: install
      - task: test-http
      - task: stop

  download:
    cmds:
      - git clone https://github.com/cleverway/docker-stacks.git
      - mv docker-stacks/{{.STACK}} .
      - rm -rf docker-stacks/

  install:
    cmds:
      - cd {{.STACK}} && task install

  start:
    cmds:
      - cd {{.STACK}} && task start

  stop:
    cmds:
      - cd {{.STACK}} && task stop

  test-http:
    cmds:
      - curl -I http://localhost:8080/
