version: '2'

tasks:
  install:
    cmds:
      - chmod 777 sites/default/files sites/default/settings.php
      - docker-compose up -d
      - sleep 10
      - docker exec -u user -w /var/www/web drupal-7_web drush si standard -y --db-url=mysql://drupal:drupal@db:3306/drupal

  start:
    cmds:
      - docker-compose up -d

  stop:
    cmds:
      - docker-compose down
