version: "2"
services:
  web:
    image: $WEB_IMAGE
    restart: always
    ports:
      - "${WEB_NETWORK_PORT}:80"
    volumes:
      - ./backup:/var/www/web/backup
    container_name: "${PROJECT_NAME}_web"
    networks:
      - dockernet
networks:
  dockernet:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}
