version: '2'

tasks:
  install:
    desc: Install stack
    cmds:
      - chmod 777 files settings.php
      - docker-compose up -d
      - sleep 10
      - docker exec -u user -w /var/www/web drupal-8_web drush si standard -y --db-url=mysql://drupal:drupal@db:3306/drupal

  start:
    desc: Start stack
    cmds:
      - docker-compose up -d

  stop:
    desc: Stop stack
    cmds:
      - docker-compose down
